name: "Build Forge"
run-name: "Building forge"
on: [push]
permissions:
  actions: "write"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for forge on ${{ runner.os }}'"
      - uses: actions/checkout@v4
      - run: "./gradlew forge:build"