name: "Build Fabric"
run-name: "Building fabric"
on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for fabric on ${{ runner.os }}'"
      - uses: actions/checkout@v4
      - run: "./gradlew fabric:build"