name: "Build Fabric"
run-name: "Building fabric"
on: [push]
permissions:
  actions: "write"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for fabric on ${{ runner.os }}'"
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v2
      - run: "./gradlew fabric:build"