name: "Build Fabric"
run-name: "Building fabric"
on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for fabric on ${{ runner.os }}'"
      - run: "git clone ${{ github.repository }} repo"
      - run: "cd repo"
      - run: "echo 'Cloned ${{ github.repository }}'"
      - run: "./gradlew fabric:build"