name: "Build Quilt"
run-name: "Building Quilt"
on: [push]
permissions:
    actions: "write"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for quilt on ${{ runner.os }}'"
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v2
      - run: "./gradlew quilt:build"