name: "Build Fabric"
run-name: "Building Fabric"
on: [push]
permissions:
  actions: "write"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for fabric on ${{ runner.os }}'"
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17.0.9
      - run: "chmod +x ./gradlew"
      - run: "./gradlew fabric:build"