name: "E2E Testing"
run-name: "E2E Testing"
on: [push]
permissions:
  actions: "write"
jobs:
  cypress:
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'Building for fabric on ${{ runner.os }}'"
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17.0.9
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
      - run: "cd webclient && npm install"
      - run: "chmod +x ./gradlew"
      - run: "./gradlew fabric:build"
      - run: "nohup ./gradlew fabric:runServer >> LOG.txt &"
        # Wait until the server is started
      - run: |
          "while ! netstat -tna | grep 'LISTEN\>' | grep -q ':8080\>'; do
            sleep 10
          done"
      - run: "cd webclient && npm run cypress"
      - post: "killall java"
      - post: "cat LOG.txt"
